version: '3.7'

services:
  eureka-server:
    build:
      context: ../eureka-server
      dockerfile: Dockerfile
  discount:
    build:
      context: ../discount/
      dockerfile: Dockerfile
    depends_on:
      - eureka-server
      - db
  db:
    image: postgres
  pgadmin:
    image: dpage/pgadmin4
  booking:
    build:
      context: ../booking
      dockerfile: Dockerfile
volumes:
  postgres_data:
  pgadmin_data:




