version: '3.7'

services:
  eureka-server:
    build:
      context: ../eureka-server
      dockerfile: Dockerfile
  discount:
    build:
      context: ../booking/
      dockerfile: Dockerfile
  db:
    image: postgres
  pgadmin:
    image: dpage/pgadmin4
  booking:
    build:
      context: ../discount
      dockerfile: Dockerfile
volumes:
  postgres_data:
  pgadmin_data:




