version: '3.7'

services:
  eureka-server:
    ports:
      - '8761:8761'
    container_name: eureka-server
    networks:
      - booking-network
  db:
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ms_book
      - POSTGRES_DB=ms_discount
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - booking-network
  pgadmin:
    container_name: ms-container-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
    networks:
      - booking-network

  discount:
    ports:
      - "8002:8002"
    container_name: discount
    networks:
      - booking-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ms_discount
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    links:
      - db
  booking:
    ports:
      - "8001:8001"
    container_name: booking
    networks:
      - booking-network
    depends_on:
      - eureka-server
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:db://db:5432/ms_book
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    links:
      - db
networks:
  booking-network: